[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
chain-support = { path = "../chain-support" }
scenario-transfer = { path = "../scenarios/transfer" }
traffic = { path = "../traffic" }

clap = { version = "3.0.0-beta.5", features = ["derive"] }
env_logger = "0.8"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
