[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
chain-support = { path = "../chain-support" }
scenario-transfer = { path = "../scenarios/transfer" }
traffic = { path = "../traffic" }

actix-web = { version = "4.0.0", features = ["openssl"] }
clap = { version = "3.0.0-beta.5", features = ["derive"] }
env_logger = "0.8"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
