[package]
name = "chain-support"
version = "0.2.0"
edition = "2021"

[dependencies]
aleph_client = { git = "https://github.com/Cardinal-Cryptography/aleph-node.git", rev = "57623da69b9e1545cbe109de8042a6f57bf32bea" }
substrate-api-client = { git = "https://github.com/Cardinal-Cryptography/substrate-api-client.git", tag = "polkadot-v0.9.13.b2bfc0c3" }

tokio = { version = "1.17.0", features = [ "rt-multi-thread", "time" ] }

common = { path = "../common" }
