[workspace]

members = [
    "bin",
    "traffic",
    "chain-support",
    "common",
    "scenarios/support",
    "scenarios/transfer",
    "scenarios/multisig",
]

exclude = [
    "monitoring",
    "set_up",
]
