scenarios = [
    { ident = "ManyToMany", interval = "1 hour", scenario = { kind = "RandomTransfers", direction = "ManyToMany", granularity = "OneByOne", transfers = 20 } },
]

[environment]
node = "wss://ws.test.azero.dev"
expose_host = "127.0.0.1:8080"
