scenarios = [
    { kind = "SimpleTransfer", ident = "SimpleTransfer (7s)", interval = "7 seconds", transfer_value = 10 },
]

[environment]
node = "127.0.0.1:9944"
protocol = "ws"
expose_host = "127.0.0.1:8080"
