scenarios = [
    { kind = "SimpleTransfer", ident = "SimpleTransfer (7s)", interval = "7 seconds" },
    { kind = "SimpleTransfer", ident = "SimpleTransfer (9s)", interval = "9 seconds" },
    { kind = "SimpleTransfer", ident = "SimpleTransfer (11s)", interval = "11 seconds" },
    { kind = "SimpleTransfer", ident = "SimpleTransfer (13s)", interval = "13 seconds" },
    { kind = "SimpleTransfer", ident = "SimpleTransfer (15s)", interval = "15 seconds" },
]

[environment]
node = "127.0.0.1:9944"
protocol = "ws"
expose_host = "127.0.0.1:8080"
