scenarios = [
    { ident = "ManyToMany (10s)", interval = "10 seconds", scenario = { kind = "RandomTransfers", direction = "ManyToMany", granularity = "OneByOne", transfers = 20 } },
]

[environment]
node = "ws://127.0.0.1:9944"
expose_host = "127.0.0.1:8080"
