scenarios = [
    { kind = "SimpleTransfer", ident = "SimpleTransfer (7s)", interval = "7 seconds" },
    { kind = "RoundRobin", ident = "RoundRobin (10s)", interval = "10 seconds", passes = 3 },
]

[environment]
node = "127.0.0.1:9944"
protocol = "ws"
expose_host = "127.0.0.1:8080"
