[package]
name = "traffic"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
chrono = "0.4"
futures = "0.3"
log = { version = "0.4", features = ["std"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.17.0", features = [ "time", "rt" ] }
