version: "3.9"

services:
  backend:
    image: traffic-maker
    build:
      dockerfile: docker/backend/Dockerfile
      context: ../
    container_name: traffic-maker
    volumes:
      - type: bind
        source: ${PWD}/Timetable.toml
        target: /Timetable.toml
    environment:
      - RUST_LOG=warn
    ports:
      - "8080:8080"
    extra_hosts:
     - host.docker.internal:host-gateway

  frontend:
    image: traffic-maker-monitoring
    build:
      dockerfile: docker/frontend/Dockerfile
      context: ../
    container_name: traffic-maker-monitoring
    ports:
      - "8040:80"
