[package]
name = "common"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
parse_duration = "2.1.1"
