# As `toml` does not support deserializing to `u128`, all amounts here are supposed to be already scaled down by 10^12:
# our token has 12 decimals.

[[endowments]]
amount = 30_000
accounts = [
    { name = "//SimpleTransferSender" },
    { name = "//RoundRobin", copies = 20 },
    { name = "//Multisig", copies = 50 }
]

[[endowments]]
amount = 1_000
accounts = [
    { name = "//RandomTransfer", copies = 100 },
    { name = "//VestingSchedulesMerging", copies = 50 },
    { name = "//Vest//Source//Vest" },
    { name = "//Vest//Source//VestOther" },
]
