# As `toml` does not support deserializing to `u128` type,
# all amounts here are supposed to be already scaled down by 10^12.

[[endowments]]
amount = 30_000
accounts = [
    { name = "//SimpleTransferSender" },
    { name = "//CommonBot", copies = 20 }
]

[[endowments]]
amount = 3_000_000
accounts = [
    { name = "//WealthyBot", copies = 5 }
]
