name: Clippy + formatting + cargo test

on:
  pull_request:
    branches:
      - "**"
  push:
    # Build on push to main to (among other things) populate caches - caches are isolated by branch,
    # but the main cache is available to other branches
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  clippy-and-fmt:
    name: Clippy + formatting + cargo test
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN_VERSION }}
          override: true

      - name: Install clippy and fmt
        run: rustup component add clippy rustfmt

      - name: Restore cache
        uses: ./.github/actions/rust-cache
        with:
          target_key: debug
          cache_version: v1

      - name: Run Format Checks
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all

      - name: Run Linter
        uses: actions-rs/cargo@v1
        env:
          # https://github.com/mozilla/sccache/issues/966
          RUSTC_WRAPPER: ""
          RUSTC_WORKSPACE_WRAPPER: sccache
        with:
          command: clippy
          args: -- --no-deps -D warnings

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Cleanup cache
        uses: ./.github/actions/rust-cache-post
